title: Blog Tool
description: AI-powered blog post generator
theme: jekyll-theme-primer

# Blog settings
permalink: /:year/:month/:day/:title/
markdown: kramdown

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/hankthevc/Blog-Tool 